name: Recent Repos
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 5
          plugin_lines_sections: repositories
